spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: http://localhost:8092
          predicates:
            - Path=/verif/**

eureka:
  client:
    register-with-eureka: true

server:
  port: 8080